#!/usr/bin/env python3
"""Generate DEFLATE fixtures for tests/test_inflate.c.

Everything here is compressed by python's zlib, so a failure is a
disagreement with a reference implementation rather than with our own
reading of RFC 1951. Emitted as a C header because the test has to run
before there is any way to load a file on the target.
"""
import sys, zlib

def deflate(data, level):
    c = zlib.compressobj(level, zlib.DEFLATED, -15)   # -15 = raw, no header
    return c.compress(data) + c.flush()

def c_bytes(name, data):
    out = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i+12])
        out.append(f"    {row},")
    out.append("};")
    out.append(f"static const uint16_t {name}_len = {len(data)};")
    return "\n".join(out)

def c_text(name, data):
    esc = data.decode('ascii').replace('\\', '\\\\').replace('"', '\\"')
    parts = [esc[i:i+68] for i in range(0, len(esc), 68)]
    body = "\n    ".join(f'"{p}"' for p in parts)
    return f"static const char {name}[] =\n    {body};"

cases = []

# Stored: incompressible framing, level 0.
t = b"hello world, this is stored and not compressed at all. " * 3
cases.append(("fx_stored", deflate(t, 0), t))

# Fixed Huffman: zlib picks it for very short inputs.
t = b"abcabcabc"
cases.append(("fx_fixed", deflate(t, 1), t))

# Dynamic Huffman: a worksheet, the real case.
t = b"<row>" + b"<c r='A1'><v>1</v></c>" * 200 + b"</row>"
cases.append(("fx_sheet", deflate(t, 9), t))

# Overlapping matches: distance 1 with a long length.
t = b"x" + b"a" * 300 + b"y" + b"ab" * 200
cases.append(("fx_runs", deflate(t, 9), t))

# A back-reference most of the way across the 32 KB window.
t = b"MARKER-AT-THE-START" + b"." * 20000 + b"MARKER-AT-THE-START" + b"end"
cases.append(("fx_far", deflate(t, 9), t))

out = ['/* Generated by tools/make_inflate_fixtures.py — do not edit.',
       ' *',
       ' * Compressed by python zlib at raw-deflate settings. The _text',
       ' * arrays are the exact bytes that must come back out.',
       ' */',
       '#ifndef X16S_INFLATE_FIXTURES_H',
       '#define X16S_INFLATE_FIXTURES_H', '']
for name, comp, text in cases:
    out.append(f"/* {len(text)} bytes -> {len(comp)} */")
    out.append(c_bytes(name, comp))
    out.append(c_text(name + "_text", text))
    out.append("")
out.append("#endif")

path = sys.argv[1] if len(sys.argv) > 1 else "tests/inflate_fixtures.h"
open(path, "w").write("\n".join(out) + "\n")
print(f"wrote {path}: " + ", ".join(f"{n} {len(c)}B" for n, c, _ in cases))
